name: Deploy to VM

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
    
    - name: Deploy code via SSH with password
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no username@$VM_IP 'cd /path/to/your/app; git pull origin main'
        # Replace `username` with your VM username, and `/path/to/your/app` with the actual path

    - name: Restart Flask App
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no username@$VM_IP 'sudo systemctl restart flask-app'
        # Adjust username and service name as per your setup
